### ISSUE TITLE
Extend versification mapping to support deuterocanonical books

### ISSUE THREAD

**Issue by UnasZole** [AndBible/jsword#12]
Hi, and thanks for enabling the issues tracker on this repo !

First ticket I'd like to open (and work on in the near future) is to extend the versification mapper to support deuterocanonical books.

Currently, all versification mapping relies on the KJV bible as a universal reference : all mappings are done to and from KJV in VersificationToKJVMapper, and then the VersificationsMapper can chain that to map between two arbitrary bibles.
However, KJV is missing all deuterocanonical books, which prevents creating accurate mappings with all bibles that contain those !

The goal of this ticket is therefore the following : 
- Update the VersificationToKJVMapper, so that it actually uses the KJVA as universal reference instead of KJV. (KJVA is identical to KJV, except it includes deuterocanonical texts as additional books at the end of the Old Testament)
- Update the currently provided versification mapping properties files, to explicitly indicate all the "missing" blocks (ie the deuterocanonical books from KJVA that would be missing from these versifications)
- Provide a versification mapping properties file for Catholic versification.

One of the objective is to be able to keep alignment when reading the books of Daniel or Esther between two bibles which have different approaches for their deuterocanonical contents (eg. Catholic where the deuterocanonical additions are integrated into the main text, vs KJVA where they are in a separate book).

**Comment by tuomas2** [comment]
PR merged to develop
